### ISSUE TITLE
Concatenate certificates into certificate chain 

### ISSUE THREAD

**Issue by yizha1** [Azure/notation-azure-kv#58]
### Is your feature request related to a problem?

According to [Notation plugin spec](https://github.com/notaryproject/notaryproject/blob/main/specs/plugin-extensibility.md) and [Certificate Requirement](https://github.com/notaryproject/notaryproject/blob/main/specs/signature-specification.md#certificate-requirements), AKV plugin is required to include a certificate chain in the response to Notation signing request. It is ideal to get the complete certificate chain (root CA - intermediate CA - leaf CA) from AKV. However, there are two limitations with AKV.

#### Limitations on completing certificate chains

There are two options for a user to complete a certificate chain:

1.  A user can merge the entire certificate chain when merging signed request, provided the user has brought back a .p7b file to merge (see [steps](https://learn.microsoft.com/azure/key-vault/certificates/create-certificate-signing-request))
    -  **Limitation**: If users missed merging the certificate chain when merging signed request, then users cannot merge the chain afterwards.
2.  A user can import the certificate chain when importing a certificate (see [steps]( https://learn.microsoft.com/azure/key-vault/certificates/tutorial-import-certificate))
     - **Limitation**: The private key of the leaf certificate is required to import the certificate chain.

#### Limitations on fetching certificate chains

Fetching certificate chains is only possible via the [Get Secret REST API]( https://learn.microsoft.com/rest/api/keyvault/secrets/get-secret/get-secret). It requires a broader `Secret/Get` permission, which is commonly not granted when [least privileged access]( https://learn.microsoft.com/azure/active-directory/develop/secure-least-privileged-access) is adopted.
 
On the other hand, [Get Certificate REST API]( https://learn.microsoft.com/rest/api/keyvault/certificates/get-certificate/get-certificate) only requires `Certificate/Get` permission. However, no matter whether the certificate chain is merged, only the leaf certificate is returned.

### What solution do you propose?

The proposed solution is to complete the certificate chain via the AKV plugin by concatenating the remote leaf certificate (from AKV) with the local partial chain (from local filesystem).
 
The AKV plugin should support base64 encoded X.509 (`.cer`, `.crt`, or `.pem`) format for the partial certificate chain.
 
Assuming that users have their certificates store in an AKV, here are the steps:
 
1. Users obtain the certificate files (`.pem`) of the intermediate CAs and the root CA, concatenate them into a single `cert_bundle.pem` file, and store it on the local file system.

2. Users associate the partial chain with the signing key when executing `notation key add` via the flag `--plugin-config ca_certs="<file path>"` where absolute path is required. For example
   ```sh
   notation key add "myKeyName" --plugin "azure-kv" \
       --id "keyid" --plugin-config ca_certs="/path/to/cert_bundle.pem"
   ```
3. Users sign artifacts as usual. For example,
   ```sh
   notation sign --key "myKeyName"
   ```
   The plugin config is passed by Notation to AKV plugin in the `generate-signature` request, see [spec]( https://github.com/notaryproject/notaryproject/blob/v1.0.0-rc.1/specs/plugin-extensibility.md#generate-signature).

4. Once the AKV plugin receives a `generate-signature` request, it reads the partial certificate chain from the `/path/to/certbundle.pem` file, concatenates it to the leaf certificate obtained from AKV for a complete certificate chain.

### What alternatives have you considered?

Build the certificate chain from the OS store. Since there are cross-signed certificates, building the certificate chain from the OS store could lead to a wrong certificate chain being generated, thus, users cannot validate the signature later.

### Any additional context?

**Comment by patrickzheng200** [comment]
Just sharing my thoughts on the proposed solution above:
1. Looks like we will not use the OS store to solve this issue anymore. Then, the newly proposed solution is highly dependent on users getting the rest of the certificate chain correctly and safely. (The user would start from a CA issued leaf certificate.) 
2. Therefore, we need a tutorial to tell users how to do it. Since this happens even before calling the `notation key add` command, looks like this tutorial needs to be inside Notation. Without any tutorial, users might have to try multiple times only to get a correct cert chain in order to Sign with notation. Usability is my top concern here. 
3. Note, a user might get the rest of the cert files in the chain one by one instead of a bundle. In this case, users need to know how to concatenate them. Again, we could have a doc for this. But I'm thinking if a new command in notation CLI would help, something like `notation cert chain cert1 cert2 rootCert` command.
4. Since notation will always validate the full cert chain on Sign and Verify, it seems that AKV plugin could just skip the validation process. (This is an implementation detail though) @JeyJeyGao

**Comment by JeyJeyGao** [comment]
I think we can build shared library to manipulate the cert chain, including concatenate the leaf cert and cert bundle, fetch the cert chain from OS and validate the cert chain for notation, so all the notation plugin implementer can share the library, or used by who want a cert chain.

**Comment by JeyJeyGao** [comment]
Do we need to mention that `certbundle.crt` is in PEM format.

**Comment by yizha1** [comment]
Thanks @JeyJeyGao  and @patrickzheng200, the issue description was updated accordingly.

**Comment by yizha1** [comment]
Thanks @shizhMSFT for providing offline comments. I accepted all the comments.

**Comment by gillg** [comment]
Great to see this subject moving forward :)
In my opinion, the proposal of @JeyJeyGao is probably a better long term solution for any other plugins which will have the same kind of issues.

For your concerns @patrickzheng200 I would propose to don't care about the certs order in the bundle. To me, it's a simple CA bundle like it already exists on Linux, the plugin (or lib) in charge to reassemble le chain should just search the certs on it. If you have some cross signing you just use a smaller bundle to avoid a wrong computation, but if you don't you could even point /etc/certificates/ca.pem in Linux context.

By the way in term of usability, using cross signing is more worrying to me... When it happened with Let's encrypt for their "smooth" CA migration some years ago, it has been a drama in the dev community to understand the root cause and the side effects of cross signing ! So someone using this "advanced" approach should not be worried about generating a bundle 😃 
But if there is an utility on notation to manage certs it's not a bad idea at all anyway.
